/**
 * TSyringe DI Container初期化
 * アプリケーション起動時に必ずコンテナを初期化する
 */
import 'reflect-metadata';

// DIコンテナ設定をインポート

import { geistMonoFont, geistSansFont } from '@/app/fonts';
import '@/app/globals.css';
import { AppToast } from '@/components/atom/general/toast/AppToast';
import { BodyContainer } from '@/components/navigation/body/BodyContainer';
import { BodyContainerClient } from '@/components/navigation/body/BodyContainerClient';
import { SessionProvider } from '@/components/providers/SessionProvider';
import '@/layers/infrastructure/di/container';

import {
  ThemeConfig,
  ThemeModeScript,
  ThemeProvider,
  createTheme,
} from 'flowbite-react';
import type { Metadata } from 'next';

/**
 * flowbiteのtheme設定
 */
const theme = createTheme({
  button: {
    color: {
      primary: 'bg-primary hover:bg-primary2 text-white',
      error: 'bg-error hover:bg-error2 text-white',
      warn: 'bg-warn hover:bg-warn2 text-black',
    },
  },
  sidebar: {
    root: {
      base: 'h-full overflow-y-auto overflow-x-hidden rounded-none bg-gray-50 px-3 py-4 dark:bg-gray-800',
    },
  },
});

/**
 * アプリのメタデータ
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * 全てのページで読み込まれるレイアウト
 * Server Component
 *
 * DDD/Clean Architecture パターン:
 * - DIコンテナ初期化をアプリケーション起動時に実行
 * - NextAuthのSessionProviderでセッション管理統合
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full' suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSansFont.className} ${geistMonoFont.className} antialiased h-full`}
      >
        <SessionProvider>
          <ThemeProvider theme={theme}>
            <BodyContainerClient>
              <BodyContainer>
                {children}
                <AppToast />
              </BodyContainer>
            </BodyContainerClient>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
